# Accessing Databases using Python

##### An application programming interface is a set of functions that you can call to get access to some type of servers. The SQL API consists of library function calls as an application programming interface, API, for the DBMS.

# Writing code using DB-API

#### Connection objects (you use connection objects to connect to a database and manage your transactions)
- Database connections
- Manage transactions

#### Cursor objects (cursor objects are used to run queries)
- Database Queries

#### Connection methods
- cursor() *returns a new cursor object using the connection*
- commit() *is used to commit any pending transaction to the database*
- rollback() *causes the database to roll back to the start of any pending transaction*
- close() *close a database connection*

#### Cursor methods (cursors are used to scan through the results of a database)
- callproc() 
- execute()
- executemany()
- fetchone()
- fetchmany()
- fetchall()
- nextset()
- arraysize()
- close()

In [ ]:
# First, you import your database module by using the connect API from that module
from dbmodule import connect

# Create connection object: To open a connection to the database, you use the connection function and pass in the parameters that is the database name, username, and password. The connect function returns connection object.
Connection=
connect('databasename','username','pswd')

# Create a cursor object
Cursor=connection.cursor()

# Run Queries
Cursor.execute('select * from mytable')
Results=cursor.fetchall()

# Free resources
Cursor.close()
Connection.close()

***

# Creating tables, loading data and querying data
ibm_db.exec_immediate(conn, "select * from SAMPLE")

*In this example, the first parameter is for the connection, the second one is the SQL query or the statement, and the third parameter for options, is Optional and has not been specified here*

In [ ]:
# Analyzing data with Python
import pandas

df.describe(include=all)

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

#Categorical scatterplots
plot=sns.swarmplot(x="Category", y='Sodium', data=df)
plt.setp(plot.get_xticklabels(), rotation=70)
plt.title('Sodium Content')
plt.show()

df['Sodium].describe()
df['Sodium'].idmax()
df.at[82,'item']

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

plot=sns.jointplot(x="Protein", y='Total Fat', data=df)
plot.show()

***

In [ ]:
#Which borrowers has a book out of loan?

Borrower.Borrower_ID = Loan.Borrower_ID

# Types of Joins:
- Inner Join
- Outer Join
	- Left Outer Join
	- Right Outer Join
	- Full Outer Join

An **inner join** matches the results from two tables and displays only the result set that matches the criteria specified in the query. An inner join returns only the rows that match.

**SELECT** B.BORROWER_ID, B.LASTNAME, B.COUNTRY,  
  L.BORROWER_ID, L.LOAN_DATE  
**FROM** BORROWER B **INNER JOIN** LOAN L  
  **ON** B.BORROWER_ID = L.BORROWER_ID

### Joining Three Tables:
**SELECT** B.LASTNAME, L.COPY_ID, C.STATUS  
**FROM** BORROWER B  
  **INNER JOIN** LOAN L **ON** B.BORROWER_ID = L.BORROWER_ID  
  **INNER JOIN** COPY C **ON** L.COPY_ID = C.COPY_ID

A **left join** matches the results from two tables and displays all the rows from the left table, and combines the information with rows from the right table that match the criteria specified in the query.

**SELECT** B.BORROWER_ID, B.LASTNAME, B.COUNTRY,  
  L.BORROWER_ID, L.LOAN_DATE  
**FROM** BORROWER B **LEFT JOIN** LOAN L  
  **ON** B.BORROWER_ID = L.BORROWER_ID

A **right join** matches the results from two tables and displays all the rows from the right table and combines the information with rows from the left table that matched the criteria specified in the query.

The **full join** keyword returns all rows from both tables.
***

In [ ]:
# When using SQL magic you can use the %%SQL in the first line of the cell in Jupiter Notebooks. It implies that the rest of the content of the cell is to be interpreted by SQL magic

%%sql
select "Id", "Name_of_Dog",
from dogs
where "Name_of_Dog" = 'Huggy'

****

# Python for Data Science and AI
## Types
Type | Definition | Expression
:---: | :---: | :---: |
11 | integer | int
21.21 | No. decimal | float
"Hello" | word | str

### Convertions
float(2) = 2.0  
int(1.1) = 1  
int('1') = 1  
int('A') = error  
str(1) = "1"  
str(4.5) = '4.5'

In [ ]:
# Boolean = True or False
type(True):bool
int(True)=1, int(False)=0
bool(1)=True, bool(0)=False

## String Operations
Michael Jackson= 0-17\
Michael = 0-6\
Espacio = 7\
Jackson = 8-14

In [3]:
name= "Michael Jackson"
name[0:4], name[8:12];
name[::2]

'McalJcsn'

In [4]:
name[0:5:2]

'Mca'

In [5]:
len("Michael Jackson")

15

In [8]:
Name="Michael Jackson"
Statement=Name + " is the best"
print(Statement)

Michael Jackson is the best


In [11]:
3*"Michael Jackson "

'Michael Jackson Michael Jackson Michael Jackson '

In [15]:
print("Michael Jackson \n is the best")

Michael Jackson 
 is the best


In [14]:
print("Michael Jackson \t is the best")

Michael Jackson 	 is the best


In [20]:
a="Thriller is the sixth studio album"
b=a.upper()
print(b)

THRILLER IS THE SIXTH STUDIO ALBUM


In [21]:
a="Michael Jackson is the best"
b=a.replace("Michael", "Janet")
print(b)

Janet Jackson is the best


In [25]:
Name="Michael Jackson"

In [23]:
Name.find("el")

5

In [24]:
Name.find("Jack")

8

In [26]:
#The method find, find substrings. The argument is the substring you would like to find.
#The output is the first index of the sequence. We can find the substring Jack.
#If the substring is not in the string, the output is negative one.
Name.find("&+D")

-1

In [34]:
"123".replace("12", "ab")

'ab3'

## List and Tuples

In [1]:
L=["Michael Jackson", 10.1, 1982]
L.extend(["pop",10])

In [2]:
L

['Michael Jackson', 10.1, 1982, 'pop', 10]

In [4]:
L.append([1982])

In [5]:
L

['Michael Jackson', 10.1, 1982, 'pop', 10, [1982]]

In [6]:
A=["disco",10,1.2]
A[0]="Hard Rock"
A

['Hard Rock', 10, 1.2]

In [7]:
del(A[0])

In [8]:
A

[10, 1.2]

In [9]:
"A,B,C,D".split(",")

['A', 'B', 'C', 'D']

In [2]:
A=((1),[2,3],[4])
A[2][0]

4

In [3]:
len(("disco",10,1.2, "hard rock",10))

5

## Dictionaries
- **Dictionaries** are doneted with curly Brackets {}
- The **keys** have to be *immutable and unique*
- The **values** can be immutable, mutable and duplicates
- Each **key** and **value** pair is separated by a comma

In [ ]:
{"key1":1,"key2":"2","key3"[3,3,3],"key4":(4,4,4),("key5):5}

In [ ]:
# Add:
DICT["Graduation"]="2007"

# Delate:
del(DICT["Thriller"]

# Ask:
"The Bodyguard" in DICT
True

# see all the keys or values in the dictionary
DICT.keys()
DICT.values()

## Sets
- Sets are a type of collection
	- This means that like lists and tuples you can input different Python types
- Unlike lists and tuples they are unordered
	- This means sets do not record element position
- Sets only have unique elements
	- This means there is only one of a particular element in a set

In [ ]:
set()

A={"Thriller","Back in Black","AC/DC"}
A.add("NSYNC")
A.remove()

"AC/DC" in A
True

album_set_1={"AC/DC","Black in Black","Thriller"}
album_set_2={"AC/DC","Black in Black","The Dark Side of the Moon"}
album_set_3=album_set_1 & album_set_2
album_set_3={"AC/DC","Black in Black"}

album_set_1.union(album_set_2)
{"AC/DC","Black in Black","The Dark Side of the Moon","Thriller"}

album_set_3.issubset(album_set_1)
True

In [5]:
V={'A','B'}
V.add('C')
V

{'A', 'B', 'C'}

In [12]:
age=17
if age>18:
    print("you can enter")
elif age==18:
    print("go see Pink Floyd")
else:
    print("go see Meat Loaf")
print("move on")

go see Meat Loaf
move on


In [7]:
age = 18

if age > 18:
    print("you can enter" )
elif age == 18:
    print("go see Pink Floyd")
else:
    print("go see Meat Loaf" )
    
print("move on")

go see Pink Floyd
move on


## Logic Operators

#### We see the OR operator only produces a false if all the Boolean values are false.
#### We see the AND operator only produces a true if all the Boolean values are true.

In [15]:
x=1
if (x!=1):
    print("Hello")
else:
    print("Hi")
print("Mike")

Hi
Mike


In [16]:
x="Go"

if(x=="Go"):

  print('Go ')

else:

  print('Stop')

print('Mike')

Go 
Mike


In [21]:
x=1
x>5

False

# Loops

In [22]:
# Use for loop to change the elements in list

squares = ['red', 'yellow', 'green', 'purple', 'blue']

for i in range(0, 5):
    print("Before square ", i, 'is',  squares[i])
    squares[i] = 'weight'
    print("After square ", i, 'is',  squares[i])

Before square  0 is red
After square  0 is weight
Before square  1 is yellow
After square  1 is weight
Before square  2 is green
After square  2 is weight
Before square  3 is purple
After square  3 is weight
Before square  4 is blue
After square  4 is weight


In [23]:
# Loop through the list and iterate on both index and element value

squares=['red', 'yellow', 'green', 'purple', 'blue']

for i, square in enumerate(squares):
    print(i, square)

0 red
1 yellow
2 green
3 purple
4 blue


In [24]:
# While Loop Example

dates = [1982, 1980, 1973, 2000]

i = 0
year = 0

while(year != 1973):
    year = dates[i]
    i = i + 1
    print(year)

print("It took ", i ,"repetitions to get out of loop.")

1982
1980
1973
It took  3 repetitions to get out of loop.


#### create loop: **for** *i* **in** list

In [25]:
# Write a while loop to display the values of the Rating of an album playlist stored in the list PlayListRatings.
# If the score is less than 6, exit the loop.
# The list PlayListRatings is given by: PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]

PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]
i=1
rating=PlayListRatings[0]
while(rating >= 6):
    rating = PlayListRatings[i]
    i = i + 1
    print(rating)

print("It took ", i ,"repetitions to get out of loop.")

9.5
10
8
7.5
5
It took  6 repetitions to get out of loop.


In [26]:
PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]
i = 1
Rating = PlayListRatings[0]
while(Rating >= 6):
    print(Rating)
    Rating = PlayListRatings[i]
    i = i + 1

10
9.5
10
8
7.5


In [27]:
# Write a while loop to copy the strings 'orange' of the list squares to the list new_squares.
# Stop and exit the loop if the value on the list is not 'orange':

squares = ['orange', 'orange', 'purple', 'blue ', 'orange']
new_squares = []
i = 0
while(squares[i] == 'orange'):
    new_squares.append(squares[i])
    i = i + 1
print (new_squares)

['orange', 'orange']


In [28]:
A=['1','2','3']

for a in A:

  print(2*a)

11
22
33


In [29]:
x=0
while(x<2):
  print(x)
  x=x+1

0
1


In [30]:
for i,x in enumerate(['A','B','C']):
    print(i,2*x)

0 AA
1 BB
2 CC


In [31]:
for i in range(1,5):
    if (i!=2):
        print(i)

1
3
4


In [4]:
def Print(A):
    for a in A:
        print(a+'1')
        
Print(['a','b','c'])

a1
b1
c1


In [6]:
def hello():
    print("hello")

In [7]:
a=1

def do(x):
    return(x+a)

print(do(1))

2


## Objects and Classes

### Built-in Types in Python
- every object has:
 - a type
 - an internal data representation (a blueprint)
 - a set of procedures for interacting with thee object (methods)
- an object is an instance of a particular type

### Methods
- A class or type's methods are functions that every instance of that class or type provides
- It's how you interact with the data in a object
- Sorting is an example of a method that interacts with the data in the object

In [ ]:
# Class Definition / Name of Class / Class parent - Will just be object for this coerce
class Circle(object):

The next step is a special method called a constructor <code>&#95;&#95;init&#95;&#95;</code>, which is used to initialize the object. The input are data attributes. The term <code>self</code> contains all the attributes in the set. For example the <code>self.color</code> gives the  value of the attribute color and <code>self.radius</code> will give you the radius of the object. We also have the method <code>add_radius()</code> with the parameter <code>r</code>, the method adds the value of <code>r</code> to the attribute radius. To access the radius we use the syntax <code>self.radius</code>. The labeled syntax is summarized in Figure 5:

In [ ]:
# Define your class
class Circle(object):

#Data attributes used to initialize object:
def_init_(self,radius,color):
 self.radius=radius;
 self.color=color;

#Method used to add r to radius
def add_radius(self,r):
 self.radius=self.radius+r
 return(self.rarius)

In [8]:
class Points(object):
  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p1=Points(1,2)
p1.print_point()

x= 1  y= 2


In [9]:
class Points(object):
  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p2=Points(1,2)

p2.x=2

p2.print_point()

x= 2  y= 2


In [1]:
import numpy as np

In [3]:
a=np.array([0,1,2,3,4])

In [5]:
a.shape #The attribute shape is a tuple of integers indicating the size of the array in each dimension

(5,)

In [ ]:
a.size:5 #The attribute size is the number of elements in the array. As there are five elements the result is five
a.ndim:1 #The attribute ndim represents the number of array dimensions or the rank of the array, in this case one

In [ ]:
#Indexing and Slicing

c=np.array([20,1,2,3,4])
c:array([20,1,2,3,4])

c=[0]=100
c:array([100,1,2,3,4])

c=[4]=0
c:array([100,1,2,3,0])

d=c[1:4]
d:array([1,2,3])

c:array([100,1,2,3,0])
c[3:5]=300,400
c:array([100,1,2,300,400])

In [ ]:
# operations on one-dimensional arrays

u=np.array([1,0])
v=np.array([0,1])
z=u+v
z:array([1,1])

y=np.array([1,2])
z=2*y
z:array([2,4])

u=np.array([1,2])
v=np.array([3,2])
z=u*v
z:array([3,4])

#Adding Constant to an numpy Array
u=np.array([1,2,3,-1])
z=u+1
z:array([2,3,4,0])

#Universal Functions
a=np.array([1,-1,1,-1])
mean_a=a.mean()

In [ ]:
#Plotting Mathematical Functions
x=np.linspace(0,2*np.pi,100)
y=np.sin(x)

import marrplotlib.pyplot as plt
%matplotlib inline
plt.plot(x,y)

In [6]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b)

0

In [7]:
a=np.array([1,1,1,1,1])
b=np.array([2,2,2,2,2])
a*b

array([2, 2, 2, 2, 2])

In [8]:
a=np.array([1,1,1,1,1])
a+10

array([11, 11, 11, 11, 11])

In [ ]:
# We can use the attribute ndim to obtain the number of axes or dimensions referred to as the rank
# Show the numpy array dimensions

A.ndim

# Attribute shape returns a tuple corresponding to the size or number of each dimension
# Show the numpy array shape

A.shape

# The total number of elements in the array is given by the attribute size
# Show the numpy array size

A.size

# Access the element on the second row and third column

A[1, 2]

or

A[1][2]

# Access the element on the first row and first column

A[0][0]

# Access the element on the first row and first and second columns

A[0][0:2]

# Access the element on the first and second rows and third column

A[0:2, 2]

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoAdd.png" width="500" />

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoDb.png" width="500" />

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoMul.png" width="500" />

In [ ]:
# We use the numpy function dot to multiply the arrays together
# Calculate the dot product

Z = np.dot(A,B)

# Calculate the sine of Z

np.sin(Z)

# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])

# Get the transposed of C

C.T

In [3]:
import numpy as np

In [4]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])

In [11]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]])
Z=np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])